### ISSUE TITLE
Update readme please

### ISSUE THREAD

**Issue by Gargo** [intelygenz/NetClient-iOS#7]
Just tried to use code samples from readme - they don't work. Example contains different sources and they work

**Comment by alexruperez** [comment]
Thanks again for the feedback @Gargo, what happened was that we used the shared instance `NetURLSession.shared`, which conforms `Net` protocol that has not defined the URL and URLRequest helpers, use an `NetURLSession()` instance instead of the `NetURLSession.shared` instance as the README.md now explains and everything will work ok.
